<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-Banking.Worker-f2bc1431-a371-4a5c-9c6b-f8404cb14a87</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MassTransit" Version="8.2.5" />
    <PackageReference Include="MassTransit.RabbitMQ" Version="8.2.5" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="8.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Banking.Application\Banking.Application.csproj" />
    <ProjectReference Include="..\Banking.Infrastructure\Banking.Infrastructure.csproj" />
    <ProjectReference Include="..\Banking.Domain\Banking.Domain.csproj" />
  </ItemGroup>
</Project>
